UI_Layer/Models/ErrorViewModel.cs
using System;

namespace UI_Layer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UI_Layer/Controllers/EmployController.cs
//using Microsoft.AspNetCore.Mvc;
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Threading.Tasks;

//namespace UI_Layer.Controllers
//{
//    public class EmployController : Controller
//    {
//        //public IActionResult Index()
//        //{
//        //    return View();
//        //}

//    }
//}

using Entity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace NewsAdManagementSystem_UI.Controllers
{
    public class EmployController : Controller
    {
        private IConfiguration _configuration;
        public EmployController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        #region ShowEmployDetails
        public async Task<IActionResult> ShowEmployDetails()//Select*from EmployDetails
        {
            IEnumerable<EmployDetails> employResult = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "Employ/GetEmployDetails";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        employResult = JsonConvert.DeserializeObject<IEnumerable<EmployDetails>>(result);
                    }
                }
            }
            return View(employResult);
        }
        #endregion ShowEmployDetails

        #region Register
        //GET Method
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Register(EmployDetails employDetails)//Insertion into EmployDetails values
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(employDetails), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "Employ/AddEmploy";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Saved Successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries!";
                    }
                }
            }
            return View();
        }
        #endregion Register

        #region EditEmployDetails

        //GET Method
        [HttpGet]
        public async Task<IActionResult> EditEmployDetails(int EmpID)//Update EmployDetails 
        {
            EmployDetails employDetails = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "Employ/GetEmployDetailsByID?EmpID=" + EmpID;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        employDetails = JsonConvert.DeserializeObject<EmployDetails>(result);

                    }
                }
            }
            return View(employDetails);
        }

        //POST Method
        [HttpPost]
        public async Task<IActionResult> EditEmployDetails(EmployDetails employDetails)
        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(employDetails), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "Employ/UpdateEmploy";
                using (var response = await client.PutAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Updated Successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries!";
                    }
                }
            }
            return View(employDetails);
        }
        #endregion EditEmployDetails

        #region DeleteEmployDetails
        public async Task<IActionResult> DeleteEmployDetails(int EmpID)//Delete EmployDetails 
        {
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "Employ/DeleteEmploy?EmpID=" + EmpID;
                using (var response = await client.DeleteAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        ViewBag.message = "Deleted Successfully";
                    }
                }
            }
            return RedirectToAction("ShowEmployDetails");

        }
        #endregion DeleteEmployDetails

        #region Login
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(EmployDetails employDetails)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(employDetails), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "Employ/Login";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                        return RedirectToAction("ShowEmployDetails");
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong credentials!";
                    }
                }
            }
            return View();
        }
        #endregion Login
    }
}

UI_Layer/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using UI_Layer.Models;

namespace UI_Layer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UI_Layer/Views/Employ/ShowEmployDetails.cshtml
@model IEnumerable<Entity.Models.EmployDetails>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@*<td><a asp-controller="Employ" asp-action="ShowEmployDetails" class="btn btn-info">Manage Advertisement Entries</a></td>*@
<div class="row">
    <div class="col-12">
        <h3>Employee Details</h3>
        <hr />
    </div>

</div>
<div>@ViewBag.message</div>
<table class="table table-bordered table-hover table-light">
    <thead>
        <tr>
            <th>Employee ID</th>
            <th>Full Name</th>
            <th>Contact Number</th>
            <th>EmailID</th>
            <th>Country</th>
            <th>State</th>
            <th>City</th>
            <th>Password</th>
            
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.EmpID</td>
                <td>@item.EmpName</td>
                <td>@item.EmpContactNo</td>
                <td>@item.EmailID</td>
                <td>@item.Country</td>
                <td>@item.State</td>
                <td>@item.City</td>
                <td>@item.Pwd</td>
                


                <td>

                    <a asp-controller="Employ" asp-action="EditEmployDetails" asp-route-EmpID="@item.EmpID">
                        <span class="btn btn-sm btn-primary">
                            <i class="fade fade-edit" aria-hidden="true"></i>
                        </span>
                    </a>
                </td>
                <td>
                    <a asp-controller="Employ" asp-action="DeleteEmployDetails" asp-route-EmpID="@item.EmpID">
                        <span class="btn btn-sm btn-danger">
                            <i class="fa-eye fa-trash" aria-hidden="true"></i>

                        </span>
                    </a>

                </td>

            </tr>

        }

    </tbody>
</table>

UI_Layer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UI_Layer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeDetails </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UI_Layer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employ" asp-action="ShowEmployDetails">ShowEmployDetails</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - UI_Layer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>